// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "bun":
            case "mq`?mf%=L3ql+x~^c-f=":return [img`
........................
......ffff..............
....fff22fff............
...fff2222fff...........
..fffeeeeeefff..........
..ffe222222eef..........
..fe2ffffff2ef..........
..ffffeeeeffff..........
.ffefbf44fbfeff.........
.fee41fddf14eef.........
fdfeeddddd4eff..........
fbffee444edd4e..........
fbf4f2222edde...........
fcf.f22cccee............
.ff.f44cdc4f............
....fffddcff............
.....fddcff.............
....cddc................
....cdc.................
....cc..................
........................
........................
........................
........................
`, img`
........................
........................
.......ff...............
.....ff22ff.............
...fff2222fff...........
..fff222222fff..........
..fff222222fff..........
..feeeeeeeeeeff.........
.ffe22222222eff.........
.fffffeeeefffff.........
fdfefbf44fbfeff.........
fbfe41fddf14ef..........
fbffe4dddd4efe..........
fcfef22222f4e...........
.ff4f44554f4e...........
....ffffffdde...........
.....ffffedde...........
..11......ee............
..111....ccc............
..11111.cc1cc...........
...111111c1c............
....11111c1c............
.....1111c1c............
.......11c1c............
`, img`
......ffff..............
....fff22fff............
...fff2222fff...........
..fffeeeeeefff..........
..ffe222222eef..........
..fe2ffffff2ef..........
..ffffeeeeffff......ccc.
.ffefbf44fbfeff....cddc.
.ffefbf44fbfeff...cddc1.
.fee4dddddd4eef.ccddc11.
fdfeeddddd4eeffecddc.11.
fbffee4444ee4fddccc..11.
fbf4f222222f1edde....11.
fcf.f222222f44ee.....11.
.ff.f445544f........111.
....ffffffff.......1111.
.....ff..ff.......1111..
...1.............11111..
...111.........111111...
....111111111111111.....
........................
........................
........................
........................
`, img`
......ffff..............
....fff22fff............
...fff2222fff...........
..fffeeeeeefff..........
..ffe222222eef..........
..fe2ffffff2ef..........
..ffffeeeeffff..........
.ffefbf44fbfeff.........
.fee41fddf14eef.........
..feeddddddeef..........
...fee4444eef...........
..e4f222222f4e..........
..4df222222fd4..........
..44f445544f44..........
.....ffffff.............
.....ff..ff.............
........................
........................
........................
........................
........................
........................
........................
........................
`];
        }
        return null;
    })

}
// Auto-generated code. Do not edit.
