enum ActionKind {
    Walking,
    Idle,
    Jumping
}
controller.combos.attachCombo("right+a", function () {
    animation.runImageAnimation(
    mySprite,
    [img`
        ....ffffff..............
        ..ffeeeef2f.............
        .ffeeeef222f............
        .feeeffeeeef...cc.......
        .ffffee2222ef.cdc.......
        .fe222ffffe2fcddc.......
        fffffffeeeffcddc........
        ffe44ebf44ecddc.........
        fee4d41fddecdc..........
        .feee4dddedccc..........
        ..ffee44e4dde...........
        ...f222244ee............
        ...f2222e2f.............
        ...f444455f.............
        ....ffffff..............
        .....fff................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        .......fff..............
        ....fffff2f...11........
        ..ffeeeee22ff.111.......
        .ffeeeeee222ff.1111.....
        .feeeefffeeeef.11111....
        .fffffeee2222ef.1111....
        fffe222fffffe2f.11111...
        fffffffffeeefff..111cc..
        fefe44ebbf44eef..1ccdc..
        .fee4d4bbfddef..c1ddcc..
        ..feee4dddddfeecdddc....
        ...f2222222eeddcdcc.....
        ...f444445e44ddccc......
        ...ffffffffeeee.........
        ...fff...ff.............
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `,img`
        .......ff...............
        ....ffff2ff.............
        ..ffeeeef2ff...1........
        .ffeeeeef22ff.111.......
        .feeeeffeeeef.1111......
        .fffffee2222ef.1111.....
        fffe222ffffe2f.1111.....
        ffffffffeeefff..111.....
        fefe44ebf44eef..1111....
        .fee4d4bfddef...1111....
        ..feee4dddee.c...111....
        ...f2222eeddeccccccc....
        ...f444e44ddecddddd.....
        ...fffffeeee.ccccc......
        ..ffffffff...c..........
        ..fff..ff...............
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `,img`
        ....ffffff..............
        ..ffeeeef2f....1........
        .ffeeeef222f...11.......
        .feeeffeeeef..111.......
        .ffffee2222ef.111.......
        .fe222ffffe2f.111.......
        fffffffeeefff.111.......
        ffe44ebf44eef.111.......
        fee4d41fddef.111........
        .feee4ddddf..111........
        ..fdde444ef.1111........
        ..fdde22ccc.111.........
        ...eef22cdc1111.........
        ...f4444cddc11..........
        ....fffffcddc...........
        .....fff..cddc..........
        ...........cdc..........
        ............cc..........
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ......ffffff............
        ....ffeeeef2f...........
        ...ffeeeef222f..........
        ...feeeffeeeef..........
        ...ffffee2222ef.........
        ...fe222ffffe2f.........
        ..fffffffeeefff.........
        ..ffe44ebf44eef.........
        ..fee4d41fddef..........
        ...feeeeedddf...........
        .....f4dde4ef...........
        .....fedde22f...........
        ....fffeef55ff..........
        ....ffffffffff..........
        .....ff...fff...........
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `],
    100,
    false
    )
})
controller.combos.attachCombo("left+a", function () {
    animation.runImageAnimation(
    mySprite,
    [img`
        ..............ffffff....
        .............f2feeeeff..
        ............f222feeeeff.
        .......cc...feeeeffeeef.
        .......cdc.fe2222eeffff.
        .......cddcf2effff222ef.
        ........cddcffeeefffffff
        .........cddce44fbe44eff
        ..........cdceddf14d4eef
        ..........cccdeddd4eeef.
        ...........edd4e44eeff..
        ............ee442222f...
        .............f2e2222f...
        .............f554444f...
        ..............ffffff....
        ................fff.....
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ..............fff.......
        ........11...f2fffff....
        .......111.ff22eeeeeff..
        .....1111.ff222eeeeeeff.
        ....11111.feeeefffeeeef.
        ....1111.fe2222eeefffff.
        ...11111.f2efffff222efff
        ..cc111..fffeeefffffffff
        ..cdcc1..fee44fbbe44efef
        ..ccdd1c..feddfbb4d4eef.
        ....cdddceefddddd4eeef..
        .....ccdcddee2222222f...
        ......cccdd44e544444f...
        .........eeeeffffffff...
        .............ff...fff...
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `,img`
        ...............ff.......
        .............ff2ffff....
        ........1...ff2feeeeff..
        .......111.ff22feeeeeff.
        ......1111.feeeeffeeeef.
        .....1111.fe2222eefffff.
        .....1111.f2effff222efff
        .....111..fffeeeffffffff
        ....1111..fee44fbe44efef
        ....1111...feddfb4d4eef.
        ....111...c.eeddd4eeef..
        ....ccccccceddee2222f...
        .....dddddcedd44e444f...
        ......ccccc.eeeefffff...
        ..........c...ffffffff..
        ...............ff..fff..
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `,img`
        ..............ffffff....
        ........1....f2feeeeff..
        .......11...f222feeeeff.
        .......111..feeeeffeeef.
        .......111.fe2222eeffff.
        .......111.f2effff222ef.
        .......111.fffeeefffffff
        .......111.fee44fbe44eff
        ........111.feddf14d4eef
        ........111..fdddd4eeef.
        ........1111.fe444eddf..
        .........111.ccc22eddf..
        .........1111cdc22fee...
        ..........11cddc4444f...
        ...........cddcfffff....
        ..........cddc..fff.....
        ..........cdc...........
        ..........cc............
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        .....ffffff.............
        ....f2feeeeff...........
        ...f222feeeeff..........
        ...feeeeffeeef..........
        ..fe2222eeffff..........
        ..f2effff222ef..........
        ..fffeeefffffff.........
        ..fee44fbe44eff.........
        ...feddf14d4eef.........
        ....fdddeeeeef..........
        ....fe4edd4f............
        ....f22eddef............
        ...ff55feefff...........
        ...ffffffffff...........
        ....fff...ff............
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `],
    100,
    false
    )
})
controller.up.onEvent(ControllerButtonEvent.Pressed, function () {
    mySprite.setImage(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . f f f f . . . . . . 
        . . . . f f e e e e f f . . . . 
        . . . f e e e f f e e e f . . . 
        . . . f f f f 2 2 f f f f . . . 
        . . f f e 2 e 2 2 e 2 e f f . . 
        . . f e 2 f 2 f f f 2 f e f . . 
        . . f f f 2 f e e 2 2 f f f . . 
        . . f e 2 f f e e 2 f e e f . . 
        . f f e f f e e e f e e e f f . 
        . f f e e e e e e e e e e f f . 
        . . . f e e e e e e e e f . . . 
        . . . e f f f f f f f f 4 e . . 
        . . . 4 f 2 2 2 2 2 e d d 4 . . 
        . . . e f f f f f f e e 4 . . . 
        . . . . f f f . . . . . . . . . 
        `)
})
controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    mySprite.setImage(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . f f f f . . . . . . 
        . . . . f f f 2 2 f f f . . . . 
        . . . f f f 2 2 2 2 f f f . . . 
        . . f f f e e e e e e f f f . . 
        . . f e e 2 2 2 2 2 2 e f f . . 
        . f f e 2 f f f f f f 2 e f f . 
        . f f f f f e e e e f f f f f . 
        . . f e f b f 4 4 f b f e f . . 
        . . f e 4 1 f d d f 1 4 e f . . 
        . . e f f f f d d d 4 e f . . . 
        . . f d d d d f 2 2 2 f e f . . 
        . . f b b b b f 2 2 2 f 4 e . . 
        . . f b b b b f 5 4 4 f . . . . 
        . . . f c c f f f f f f . . . . 
        . . . . f f . . . f f f . . . . 
        `)
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    mySprite,
    [img`
        ........................
        .....ffff...............
        ...fff22fff.............
        ..fff2222fff............
        .fffeeeeeefff...........
        .ffe222222eef...........
        .fe2ffffff2ef...........
        .ffffeeeeffff...........
        ffefbf44fbfeff..........
        fee41fddf14eef..........
        .ffffdddddeef...........
        fddddf444eef............
        fbbbbf2222f4e...........
        fbbbbf2222fd4...........
        .fccf45544f44...........
        ..ffffffff..............
        ....ff..ff..............
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ......ffff..............
        ....fff22fff............
        ...fff2222fff...........
        ..fffeeeeeefff..........
        ..ffe222222eef..........
        ..fe2ffffff2ef..........
        ..ffffeeeeffff..........
        .ffefbf44fbfeff.........
        .fee41fddf14eef.........
        fdfeeddddd4eff..........
        fbffee444edd4e..........
        fbf4f2222edde...........
        fcf.f22cccee............
        .ff.f44cdc4f............
        ....fffddcff............
        .....fddcff.............
        ....cddc................
        ....cdc.................
        ....cc..................
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        .......ff...............
        .....ff22ff.............
        ...fff2222fff...........
        ..fff222222fff..........
        ..fff222222fff..........
        ..feeeeeeeeeeff.........
        .ffe22222222eff.........
        .fffffeeeefffff.........
        fdfefbf44fbfeff.........
        fbfe41fddf14ef..........
        fbffe4dddd4efe..........
        fcfef22222f4e...........
        .ff4f44554f4e...........
        ....ffffffdde...........
        .11..ffffedde...........
        ..11......ee............
        ..11.....ccc............
        ..111...cc1cc...........
        ...111...c1c............
        ...11111.c1c............
        ....11111c1c............
        ......111c1c............
        `,img`
        ......ffff..............
        ....fff22fff............
        ...fff2222fff...........
        ..fffeeeeeefff..........
        ..ffe222222eef..........
        ..fe2ffffff2ef..........
        ..ffffeeeeffff......ccc.
        .ffefbf44fbfeff....cddc.
        .ffefbf44fbfeff...cddc..
        .fee4dddddd4eef.ccddc1..
        fdfeeddddd4eeffecddc11..
        fbffee4444ee4fddccc.11..
        fbf4f222222f1edde...11..
        fcf.f222222f44ee....11..
        .ff.f445544f........11..
        ....ffffffff.......11...
        .....ff..ff......1111...
        ................11111...
        ...............1111.....
        .1..........111111......
        .111...111111111........
        ...111111111............
        ........................
        ........................
        `,img`
        ......ffff..............
        ....fff22fff............
        ...fff2222fff...........
        ..fffeeeeeefff..........
        ..ffe222222eef..........
        ..fe2ffffff2ef..........
        ..ffffeeeeffff..........
        .ffefbf44fbfeff.........
        .fee41fddf14eef.........
        ..feeddddddeef..........
        ...fee4444eef...........
        ..e4f222222f4e..........
        ..4df222222fd4..........
        ..44f445544f44..........
        .....ffffff.............
        .....ff..ff.............
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        `],
    100,
    false
    )
})
controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
    mySprite.setImage(img`
        . . . . . . . . . . . . . . . . 
        . . . . . f f f f f f . . . . . 
        . . . . f 2 f e e e e f f . . . 
        . . . f 2 2 2 f e e e e f f . . 
        . . . f e e e e f f e e e f . . 
        . . f e 2 2 2 2 e e f f f f . . 
        . . f 2 e f f f f 2 2 2 e f . . 
        . . f f f e e e f f f f f f f . 
        . . f e e 4 4 f b e 4 4 e f f . 
        . . . f e d d f 1 4 d 4 e e f . 
        . . . . f d d d e e e e e f . . 
        . . . . f e 4 e d d 4 f . . . . 
        . . . . f 2 2 e d d e f . . . . 
        . . . f f 5 5 f e e f f f . . . 
        . . . f f f f f f f f f f . . . 
        . . . . f f f . . . f f . . . . 
        `)
})
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    mySprite.setImage(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . f f f f f f . . . . 
        . . . . f f e e e e f 2 f . . . 
        . . . f f e e e e f 2 2 2 f . . 
        . . . f e e e f f e e e e f . . 
        . . . f f f f e e 2 2 2 2 e f . 
        . . . f e 2 2 2 f f f f e 2 f . 
        . . f f f f f f f e e e f f f . 
        . . f f e 4 4 e b f 4 4 e e f . 
        . . f e e 4 d 4 1 f d d e f . . 
        . . . f e e e e e d d d f . . . 
        . . . . . f 4 d d e 4 e f . . . 
        . . . . . f e d d e 2 2 f . . . 
        . . . . f f f e e f 5 5 f f . . 
        . . . . f f f f f f f f f f . . 
        . . . . . f f . . . f f f . . . 
        `)
})
controller.down.onEvent(ControllerButtonEvent.Pressed, function () {
    mySprite.setImage(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . f f f f . . . . . . 
        . . . . f f f 2 2 f f f . . . . 
        . . . f f f 2 2 2 2 f f f . . . 
        . . f f f e e e e e e f f f . . 
        . . f e e 2 2 2 2 2 2 e f f . . 
        . f f e 2 f f f f f f 2 e f f . 
        . f f f f f e e e e f f f f f . 
        . . f e f b f 4 4 f b f e f . . 
        . . f e 4 1 f d d f 1 4 e f . . 
        . . e f e 4 d d d d 4 e f . . . 
        . . e 4 d d e 2 2 2 2 f e f . . 
        . . . e d d e 2 2 2 2 f 4 e . . 
        . . . . e e f 5 5 4 4 f . . . . 
        . . . . . f f f f f f f . . . . 
        . . . . . . . . . f f f . . . . 
        `)
})
controller.combos.attachCombo("up+a", function () {
    animation.runImageAnimation(
    mySprite,
    [img`
        ................
        ................
        ................
        ................
        ......ffff......
        ....ffeeeeff....
        ...feeeffeeef...
        ..fffff22fffff..
        ..ffe2e22e2eff..
        ..fe2f2ff2f2ef..
        ..fff22ee22fff..
        .ffef2feef2feff.
        .feeffeeeefeeef.
        ..feeeeeeeeeef..
        ...feeeeeeeef...
        ..e4ffffffff4e..
        ..4df222222fd4..
        ..44f444444f44..
        .....ffffff.....
        .....ff..ff.....
        `,img`
        ................
        .....b..........
        ....bdb.........
        .111bdb.........
        1111bdffff......
        1111ffeeeeff....
        111feeeffeeef...
        ..fffff22fffff..
        ..ffe2e22e2eff..
        ..fe2f2ff2f2ef..
        ..fff22ee22fff..
        .ffef2feef2feff.
        .feeffeeeefeeef.
        ..feeeeeeeeeef..
        ...feeeeeeeef...
        ..e4ffffffff....
        ..4df222222f....
        ..44f444444f....
        .....ffffff.....
        .....ff..ff.....
        `,img`
        .........b......
        ......111db.....
        .....111bdb.....
        ...11111bdb.....
        ..111.ffffb.....
        .111ffeeeeff....
        .11feeeffeeef...
        ..fffff22fffff..
        ..ffe2e22e2eff..
        ..fe2f2ff2f2ef..
        ..fff22ee22fff..
        .ffef2feef2feff.
        .feeffeeeefeeef.
        ..feeeeeeeeeef..
        ...feeeeeeeef...
        ..e4ffffffff....
        ..4df222222f....
        ..44f444444f....
        .....ffffff.....
        .....ff..ff.....
        `,img`
        ................
        ................
        ....1111111111..
        ..111111111111bb
        ..111.ffff.11bdb
        .111ffeeeeffbdb.
        111feeeffeeefb..
        11fffff22fffff..
        1.ffe2e22e2eff..
        ..fe2f2ff2f2ef..
        ..fff22ee22fff..
        .ffef2feef2feff.
        .feeffeeeefeeef.
        ..feeeeeeeeeef..
        ...feeeeeeeef...
        ..e4ffffffff....
        ..4df222222f....
        ..44f444444f....
        .....ffffff.....
        .....ff..ff.....
        `,img`
        ................
        ......ffff......
        ....ffeeeeff....
        ...feeeffeeef...
        ...ffff22ffff...
        ..ffe2e22e2eff..
        ..fe2f2fff2fef..
        ..fff2fee22fff..
        ..fe2ffee2feef..
        .ffeffeeefeeeff.
        .ffeeeeeeeeeeff.
        ...feeeeeeeef...
        ...effffffff4e..
        ...4f22222edd4..
        ...effffffee4...
        ....fff.........
        ................
        ................
        ................
        ................
        `],
    100,
    false
    )
})
let mySprite: Sprite = null
mySprite = sprites.create(img`
    . . . . . . f f f f . . . . . . 
    . . . . f f f 2 2 f f f . . . . 
    . . . f f f 2 2 2 2 f f f . . . 
    . . f f f e e e e e e f f f . . 
    . . f f e 2 2 2 2 2 2 e e f . . 
    . . f e 2 f f f f f f 2 e f . . 
    . . f f f f e e e e f f f f . . 
    . f f e f b f 4 4 f b f e f f . 
    . f e e 4 1 f d d f 1 4 e e f . 
    . . f e e d d d d d d e e f . . 
    . . . f e e 4 4 4 4 e e f . . . 
    . . e 4 f 2 2 2 2 2 2 f 4 e . . 
    . . 4 d f 2 2 2 2 2 2 f d 4 . . 
    . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
    . . . . . f f f f f f . . . . . 
    . . . . . f f . . f f . . . . . 
    `, SpriteKind.Player)
controller.moveSprite(mySprite)
tiles.setTilemap(tilemap`level1`)
scene.cameraFollowSprite(mySprite)
